inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false
