Keyword.create(name: "ネコ")
Keyword.create(name: "ねこ")
Keyword.create(name: "猫")
Keyword.create(name: "にゃ")
Keyword.create(name: "ニャ")
Keyword.create(name: "あんず")

TextMessage.create(content: "にゃ〜")
TextMessage.create(content: "みゃ〜")
TextMessage.create(content: "んにゃー")